---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.240.0.0/16"
  serviceSubnet: "10.0.0.0/16"
  disableDefaultCNI: true
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-role.kubernetes.io/master=true"
        node-labels: "type=app"
        node-labels: "ingress-ready=true"
  image: ghcr.io/kbst/kind-eks-d:v1.18.9-kbst.1
  extraPortMappings:
# istio-port: HTTP 80
  - containerPort: 30080
    hostPort: 80
    listenAddress: "127.0.0.1"
    protocol: TCP
# istio-port: HTTPS 443
  - containerPort: 30443
    hostPort: 443
    listenAddress: "127.0.0.1"
    protocol: TCP
# istio-port: Health checks 15021 (https://istio.io/latest/docs/ops/deployment/requirements/#ports-used-by-istio)
  - containerPort: 30021
    hostPort: 15021
    listenAddress: "127.0.0.1"
    protocol: TCP
# kubernetes-dashboard
  - containerPort: 8443
    hostPort: 8443
    listenAddress: "127.0.0.1"
    protocol: TCP
# generic port for NodePort
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: worker
  image: ghcr.io/kbst/kind-eks-d:v1.18.9-kbst.1
- role: worker
  image: ghcr.io/kbst/kind-eks-d:v1.18.9-kbst.1
