apiVersion: v1
kind: Namespace
metadata:
  name: nginx-test
  labels:
    istio-injection: enabled
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: nginx-test
  name: nginx-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-test
  labels:
    app: nginx-1
  name: nginx-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-1
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-1
        version: "0.0.1"
    spec:
      serviceAccountName: nginx-1
      containers:
      - image: nginxinc/nginx-unprivileged
        name: nginx-unprivileged
        ports:
        - name: http-8080
          containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: nginx-1-index-vol
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: nginx-1-path-api-vol
          mountPath: /usr/share/nginx/html/api/index.html
          subPath: index.html
        - name: nginx-1-path-app-vol
          mountPath: /usr/share/nginx/html/app/index.html
          subPath: index.html
      volumes:
      - name: nginx-1-index-vol
        configMap: 
          name: nginx-1-index
      - name: nginx-1-path-api-vol
        configMap: 
          name: nginx-1-path-api
      - name: nginx-1-path-app-vol
        configMap: 
          name: nginx-1-path-app
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx-test
  labels:
    app: nginx-1
  name: nginx-1
spec:
  ports:
  - name: http-80-8080
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-1
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nginx-test
  name: nginx-1-index
data:
  index.html: |
    nginx-1
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nginx-test
  name: nginx-1-path-api
data:
  index.html: |
    nginx-1-path-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nginx-test
  name: nginx-1-path-app
data:
  index.html: |
    nginx-1-path-app
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   creationTimestamp: null
#   namespace: nginx-test
#   name: nginx-1-istio
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: psp:istio-restricted
# subjects:
# - kind: ServiceAccount
#   name: nginx-1
#   namespace: nginx-test